name: voice_transcriber_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  gap: ^3.0.1
  dash_flags: ^0.1.1

  # Networking
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1

  # Navigation
  go_router: ^14.1.3

  # Utils
  record: ^5.0.5
  path_provider: ^2.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  flutter_gen_runner: ^5.3.2
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/playstore.png"
  image_path_ios: "assets/icons/appstore.png"

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/
